language: node_js
node_js:
  - "0.10"
services:
  - postgresql
addons:
  postgresql: "9.3"
notifications:
  email: false
script:
  - npm run syntax
  - npm test
before_script:
  - psql -c 'create database team_stream;' -U postgres
  - cd scripts/; ./clean-slate.sh team_stream; cd ..;
after_script:
  - npm run coveralls
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/team_stream
    - AWS_BUCKET=db-team-stream
    #AWS_ACCESS_KEY
    - secure: "W7MIHYE9xzFaVL2X6EpB1gbGlBIpyT194uyOXrgutbtDcmjxBvbJlGrXDUQqvM02062IUz4O1UNBdGKNySw+/Oz9yIn5bS99QdtAf4mjy3ey+ebCB/JfFsLm63n2LrYZHCWUTv7lPx0K+ECPlYPvFUsgGa/2RmiEdpIzm9Bm0Z8="
    #AWS_SECRET_ACCESS_KEY
    - secure: "TmTChgaMUu2C4NuGF/w/uVm+DHah+702Ad+8/ngqEj4a818rAxsiMSFQXmj49yzzVzKih3Ms+fcFq7fmW9qt0aMJz+mk2YYRd3LkhgIGvyPCsN1C7ScqI0dBn981vy+1GpTejoKYudiKq8n6deYptjw5NAnBo/zDyIixCnUkZew="
