'use strict';

module.exports = [
  {method: 'get',    path: '/{param*}',                         config: require('./controllers/static/angular')},
  {method: 'post',   path: '/register',                         config: require('./controllers/users/register')},
  {method: 'post',   path: '/login',                            config: require('./controllers/users/login')},
  {method: 'delete', path: '/logout',                           config: require('./controllers/users/logout')},
  {method: 'get',    path: '/status',                           config: require('./controllers/users/status')},
  {method: 'get',    path: '/projects',                         config: require('./controllers/projects/get_projects')},
  {method: 'get',    path: '/project/{pid}',                    config: require('./controllers/projects/get_project')},
  {method: 'get',    path: '/projects/{pid}/streams',           config: require('./controllers/projects/get_streams')},
  {method: 'get',    path: '/projects/{sid}/segments',          config: require('./controllers/projects/get_segments')},
  {method: 'post',   path: '/project/create',                   config: require('./controllers/projects/create_project')},
  {method: 'post',   path: '/project/collaborator/add',         config: require('./controllers/projects/add_collaborator')},
  {method: 'post',   path: '/project/stream/create',            config: require('./controllers/projects/create_stream')},
  {method: 'put',    path: '/project/stream/edit',              config: require('./controllers/projects/edit_stream')},
  {method: 'delete', path: '/project/stream/delete/{streamId}', config: require('./controllers/projects/delete_stream')},
  {method: 'post',   path: '/project/segment/create',           config: require('./controllers/projects/create_segment')},
  {method: 'put',    path: '/project/segment/edit',             config: require('./controllers/projects/edit_segment')},
  {method: 'delete', path: '/project/segment/delete/{segId}',   config: require('./controllers/projects/delete_segment')},
  {method: 'put',    path: '/project/segment/archive',          config: require('./controllers/projects/archive_segment')},
  {method: 'get',    path: '/project/segment/archive/{segId}',  config: require('./controllers/projects/get_segment_archive')},
  {method: 'post',   path: '/project/reply/create',             config: require('./controllers/projects/create_reply')},
  {method: 'put',    path: '/project/reply/edit',               config: require('./controllers/projects/edit_reply')},
  {method: 'delete', path: '/project/reply/delete/{replyId}',   config: require('./controllers/projects/delete_reply')},
  {method: 'post',   path: '/project/attachment/add/{segId}',   config: require('./controllers/projects/add_attachment')},
  {method: 'put',    path: '/project/offline/{projectId}',      config: require('./controllers/rooms/go_offline')},
  {method: 'get',    path: '/project/room/users/{projectId}',   config: require('./controllers/rooms/get_online_users')},
  {method: 'get',    path: '/project/{projectId}/activities',   config: require('./controllers/activities/get_activities')}
];
